import images/* from sedutil/sedutil

diff --git a/images/buildUEFI64 b/images/buildUEFI64
--- a/images/buildUEFI64
+++ b/images/buildUEFI64
@@ -1,36 +1,64 @@
 #!/bin/bash
-set -x
+set -ex
 # Build a custom UEFI linux based PBA image
 ## define releases for tools
 . conf
-VERSIONINFO=`git describe --dirty`  || VERSIONINFO=tarball
-BUILDTYPE=UEFI64
-BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img
+VERSIONINFO=`git describe --dirty` || VERSIONINFO=downloaded
+BUILDTYPE=$1
+BUILDIMG=UEFI64_${1}-${VERSIONINFO}.img
+if [ "$BUILDTYPE" == "Debug" ] || [ "$BUILDTYPE" == "Release" ] ; then
+            echo "Building " $BUILDTYPE "image"
+	else
+	    echo "You must select Debug|Release"
+	    exit		
+fi
+
 
 ## check that everything is available
-[  -f scratch/${SYSLINUX}/efi64/efi/syslinux.efi ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/images/bzImage ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/images/rootfs.cpio.xz ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/target/sbin/linuxpba  ] || { echo " prereqs are not available "; exit 1; }
-[  -f scratch/buildroot/64bit/target/sbin/sedutil-cli  ] || { echo " prereqs are not available "; exit 1; }
-[  -f buildroot/syslinux.cfg ] || { echo " prereqs are not available "; exit 1; }
-  
+[ -f scratch/${SYSLINUX}/efi64/efi/syslinux.efi -a \
+  -f scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 -a \
+     -f ../LinuxPBA/dist/${BUILDTYPE}_x86_64/GNU-Linux/linuxpba -a \
+     -f ../linux/CLI/dist/${BUILDTYPE}_x86_64/GNU-Linux/sedutil-cli -a \
+      -f scratch/buildroot/PBA64/images/bzImage  -a \
+      -f buildroot/syslinux.cfg -a \
+     -f scratch/kmaps.tcz \
+  ] || { echo " prereqs are not available "; exit 1; }
+# recreate the initrd file with the latest PBA
+mkdir -p scratch/buildroot/PBA64/overlay/sbin/
+cp ../LinuxPBA/dist/${BUILDTYPE}_x86_64/GNU-Linux/linuxpba  scratch/buildroot/PBA64/overlay/sbin/linuxpba
+cp ../linux/CLI/dist/${BUILDTYPE}_x86_64/GNU-Linux/sedutil-cli  scratch/buildroot/PBA64/overlay/sbin/sedutil-cli
+[[ -d scratch/buildroot/PBA64/overlay/etc/init.d ]] || mkdir -m u=rwx,go=rx -p scratch/buildroot/PBA64/overlay/etc/init.d
+if [[ -n "$BUILD_KEYMAP" ]]; then
+cat << -END-
+#!/bin/sh
+KEYBOARD="$BUILD_KEYMAP"
+loadkmap < "/usr/share/kmap/\$KEYBOARD.kmap" && echo "Keyboard set to \$KEYBOARD" || { echo "Keyboard setup for \$KEYBOARD failed."; sleep 2; }
+-END-
+else
+echo "# Do not process /etc/init.d scripts"
+fi > scratch/buildroot/PBA64/overlay/etc/init.d/rcS
+echo "# Do not process /etc/init.d scripts" > scratch/buildroot/PBA64/overlay/etc/init.d/rcK
+chmod a=rx scratch/buildroot/PBA64/overlay/etc/init.d/rc?
+sudo unsquashfs -f -d scratch/buildroot/PBA64/overlay scratch/kmaps.tcz
+cd scratch/buildroot
+make all O=PBA64 2>&1 >PBA64.log
+cd ../..
 # Start fresh
-sudo rm -rf ${BUILDTYPE} ; mkdir ${BUILDTYPE} ; cd ${BUILDTYPE}
+sudo rm -rf UEFI64_${BUILDTYPE} ; mkdir UEFI64_${BUILDTYPE} ; cd UEFI64_${BUILDTYPE}
 # make an image file
-dd if=/dev/zero of=${BUILDIMG} bs=1M count=32
-(echo "n";echo "";echo "";echo "";echo "ef00";echo w;echo Y) | gdisk ${BUILDIMG}
+dd if=/dev/zero of=${BUILDIMG} bs=1M count=7
+(echo "n"; echo ""; echo ""; echo ""; echo "ef00"; echo w; echo Y) | gdisk ${BUILDIMG}
+
 LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
-sudo mkfs.vfat $LOOPDEV -n ${BUILDTYPE}
+sudo mkfs.vfat $LOOPDEV -n UEFI64_${BUILDTYPE}
 sudo mkdir image
 sudo mount $LOOPDEV image
 sudo chmod 777 image
 sudo mkdir -p image/EFI/boot
 sudo cp ../scratch/${SYSLINUX}/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
 sudo cp ../scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
-sudo cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
-sudo cp ../scratch/buildroot/64bit/images/rootfs.cpio.xz image/EFI/boot/
+sudo cp ../scratch/buildroot/PBA64/images/bzImage image/EFI/boot/
+sudo cp ../scratch/buildroot/PBA64/images/rootfs.cpio.xz image/EFI/boot/
 sudo cp ../buildroot/syslinux.cfg image/EFI/boot/
 sudo umount image
 sudo losetup -d $LOOPDEV
diff --git a/images/buildrescue b/images/buildrescue
--- a/images/buildrescue
+++ b/images/buildrescue
@@ -1,87 +1,72 @@
 #!/bin/bash
-set -x
+set -e
+# Build a custom tinycore bootable image
 ## define releases for tools
 . conf
-VERSIONINFO=`git describe --dirty`  || VERSIONINFO=tarball
-BUILDTYPE=RESCUE32
-ROOTDIR=32bit
-
-if [ x${1} == "xRescue32" ] ; then
-	BUILDTYPE="RESCUE32"
-	ROOTDIR="32bit"
-elif [ x${1} == "xRescue64" ] ; then
-	BUILDTYPE="RESCUE64"
-	ROOTDIR="64bit"
-else 
-	echo "NO BUILDTYPE specified defalted to Rescue32"
-fi
+PROGRAM=../../linux/CLI/dist/Release_i686/GNU-Linux/sedutil-cli
+VERSIONINFO=`git describe --dirty`
+BUILDTYPE=Rescue
 BUILDIMG=${BUILDTYPE}-${VERSIONINFO}.img
 echo "Building " $BUILDTYPE "image"
-[ -f scratch/${SYSLINUX}/bios/mbr/mbr.bin ] || { echo " prereqs are not available "; exit 1; }
-[ -x scratch/${SYSLINUX}/bios/extlinux/extlinux ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/${SYSLINUX}/efi64/efi/syslinux.efi ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/buildroot/${ROOTDIR}/images/bzImage ] || { echo " prereqs are not available "; exit 1; }
-[ -f scratch/buildroot/${ROOTDIR}/images/rootfs.cpio.xz  ] || { echo " prereqs are not available "; exit 1; }
-[ -x scratch/buildroot/${ROOTDIR}/target/sbin/linuxpba  ] || { echo " prereqs are not available "; exit 1; }
-[ -x scratch/buildroot/${ROOTDIR}/target/sbin/sedutil-cli  ] || { echo " prereqs are not available "; exit 1; }
-[ -f buildroot/syslinux.cfg ] || { echo " prereqs are not available "; exit 1; }
-[ -f UEFI64/UEFI64-*.img.gz ] || { echo " prereqs are not available "; exit 1; }
-[ -f BIOS32/BIOS32-*.img.gz ] || { echo " prereqs are not available "; exit 1; }
-#
-# Remaster the root file system
-sudo rm -rf scratch/rescuefs
-sudo rm -f scratch/buildroot/${ROOTDIR}/images/rescuefs.cpio.xz 
-mkdir scratch/rescuefs
-cd scratch/rescuefs
-xz --decompress --stdout ../buildroot/${ROOTDIR}/images/rootfs.cpio.xz | sudo cpio -i -H newc -d
-#weird permission denied on etc/issue 
-echo "* ***********************************" > /tmp/issue
-echo "* DTA sedutil rescue image ${BUILDIMG}" >> /tmp/issue
-echo "*" >> /tmp/issue
-echo "* Login as root, there is no password" >> /tmp/issue
-echo "*" >> /tmp/issue
-echo "* ***********************************" >> /tmp/issue
-sudo mv /tmp/issue etc/issue
-sudo rm etc/init.d/S99*
-sudo mkdir -p usr/sedutil
-sudo cp ../../UEFI64/UEFI64-*.img.gz usr/sedutil/
-sudo cp ../../BIOS32/BIOS32-*.img.gz usr/sedutil/
-sudo find . | sudo cpio -o -H newc | xz -9 -C crc32 -c > ../buildroot/${ROOTDIR}/images/rescuefs.cpio.xz
-cd ../..
-sudo rm -rf scratch/rescuefs
-#
+# Start fresh
 sudo rm -rf ${BUILDTYPE} ; mkdir ${BUILDTYPE} ; cd ${BUILDTYPE}
-dd if=/dev/zero of=${BUILDIMG} bs=1M count=75
-if [ ${BUILDTYPE} == "RESCUE32" ] ; then
-	(echo o;echo n;echo p;echo 1;echo "";echo "";echo a;echo 1;echo w) | fdisk -C 100 ${BUILDIMG}
-	dd if=../scratch/${SYSLINUX}/bios/mbr/mbr.bin of=${BUILDIMG} count=1 conv=notrunc bs=512
-else
-	(echo "n";echo "";echo "";echo "";echo "ef00";echo w;echo Y) | gdisk ${BUILDIMG}
-fi
+[ -f ../scratch/${SYSLINUX}/bios/mbr/mbr.bin -a \
+     -x ../scratch/${SYSLINUX}/bios/extlinux/extlinux -a \
+     -f ../scratch/core.gz -a \
+     -f ../scratch/vmlinuz -a \
+     -f ../scratch/hdparm.tcz -a \
+     -f ../scratch/kmaps.tcz -a \
+     -f ../scratch/setfont.tcz -a \
+     -f ${PROGRAM} \
+  ] || { echo " prereqs are not available "; exit 1; }
+#
+dd if=/dev/zero of=${BUILDIMG} bs=1M count=30
+(echo o;echo n;echo p;echo 1;echo "";echo "";echo a;echo 1;echo w) | fdisk -C 100 ${BUILDIMG}
+dd if=../scratch/${SYSLINUX}/bios/mbr/mbr.bin of=${BUILDIMG} count=1 conv=notrunc bs=512
 LOOPDEV=`sudo losetup --show -f -o 1048576 ${BUILDIMG}`
-if [ ${BUILDTYPE} == "RESCUE32" ] ; then
-	sudo mkfs.ext4 $LOOPDEV -L ${BUILDTYPE}
-else
-	sudo mkfs.vfat $LOOPDEV -n ${BUILDTYPE}
-fi
+sudo mkfs.ext4 $LOOPDEV -L ${BUILDTYPE}-${VERSIONINFO}
 mkdir image
 sudo mount $LOOPDEV image
 sudo chmod 777 image
-if [ ${BUILDTYPE} == "RESCUE32" ] ; then
-	sudo mkdir -p image/boot/extlinux
-	sudo ../scratch/${SYSLINUX}/bios/extlinux/extlinux --install image/boot/extlinux
-	sudo cp ../scratch/buildroot/32bit/images/bzImage  image/boot/extlinux/
-	sudo cp ../scratch/buildroot/32bit/images/rescuefs.cpio.xz image/boot/extlinux/rootfs.cpio.xz
-	sudo cp ../buildroot/syslinux.cfg image/boot/extlinux/extlinux.conf
-else
-	sudo mkdir -p image/EFI/boot
-	sudo cp ../scratch/${SYSLINUX}/efi64/efi/syslinux.efi image/EFI/boot/bootx64.efi
-	sudo cp ../scratch/${SYSLINUX}/efi64/com32/elflink/ldlinux/ldlinux.e64 image/EFI/boot/
-	sudo cp ../scratch/buildroot/64bit/images/bzImage image/EFI/boot/
-	sudo cp ../scratch/buildroot/64bit/images/rescuefs.cpio.xz image/EFI/boot/rootfs.cpio.xz
-	sudo cp ../buildroot/syslinux.cfg image/EFI/boot/
-fi	
+mkdir -p image/boot/extlinux
+sudo ../scratch/${SYSLINUX}/bios/extlinux/extlinux --install image/boot/extlinux
+cp ../scratch/vmlinuz image/boot/
+echo "default DTA" >>image/boot/extlinux/extlinux.conf
+echo "prompt 0" >>image/boot/extlinux/extlinux.conf
+echo "noescape 1" >>image/boot/extlinux/extlinux.conf
+echo "label DTA" >>image/boot/extlinux/extlinux.conf
+echo "    kernel /boot/vmlinuz" >>image/boot/extlinux/extlinux.conf
+echo "    initrd /boot/core.gz" >>image/boot/extlinux/extlinux.conf
+echo "    append loglevel=0 libata.allow_tpm=1 tinycore base norestore noswap superuser" >>image/boot/extlinux/extlinux.conf
+## Remaster the initrd
+mkdir core
+cd core
+zcat ../../scratch/core.gz | sudo cpio -i -H newc -d
+cd ..
+sudo mkdir -p core/usr/local/sbin/
+sudo unsquashfs -f -d core ../scratch/hdparm.tcz
+sudo unsquashfs -f -d core ../scratch/kmaps.tcz
+sudo unsquashfs -f -d core ../scratch/setfont.tcz
+if [[ -n "$BUILD_KEYMAP" ]]; then
+cat << -END- > core/opt/bootlocal.sh
+#!/bin/sh
+KEYBOARD="$BUILD_KEYMAP"
+loadkmap < "/usr/share/kmap/\$KEYBOARD.kmap" && echo "Keyboard set to \$KEYBOARD" || echo "Keyboard setup for \$KEYBOARD failed."
+kbd_mode -u  # Switch keyboard to UTF-8 mode
+setfont default8x16  # Load font with UTF-8 mapping info (.psfu extension)
+-END-
+chmod a=rx core/opt/bootlocal.sh
+fi
+sudo cp ${PROGRAM} core/usr/local/sbin/
+## Bundle UEFI images to /root
+for file in /sedutil/images/UEFI*/*.img.gz; do
+    zcat "$file" > core/root/"$(basename ${file%.gz})"
+done
+## now repackage it
+cd core
+sudo find | sudo cpio -o -H newc | gzip -9 > ../image/boot/core.gz
+cd ..
+sudo rm -rf core
 sudo umount image
 sudo losetup -d $LOOPDEV
 gzip ${BUILDIMG}
